export const crocodileTypes = [
  { id: "1", name: "Nile Crocodile" },
  { id: "2", name: "Saltwater Crocodile" },
  { id: "3", name: "American Crocodile" },
  { id: "4", name: "Cuban Crocodile" },
  { id: "5", name: "Morelet's Crocodile" },
  { id: "6", name: "West African Crocodile" },
  { id: "7", name: "Siamese Crocodile" },
  { id: "8", name: "Indo-Pacific Crocodile" },
  { id: "9", name: "Philippine Crocodile" },
  { id: "10", name: "New Guinea Crocodile" },
  { id: "11", name: "Australian Freshwater Crocodile" },
  { id: "12", name: "Orinoco Crocodile" },
  { id: "13", name: "Dwarf Crocodile" },
  { id: "14", name: "Spectacled Caiman" },
  { id: "15", name: "Yacare Caiman" },
  { id: "16", name: "Chinese Alligator" },
  { id: "17", name: "Black Caiman" },
  { id: "18", name: "Gharial" },
  { id: "19", name: "Mugger Crocodile" },
  { id: "20", name: "Broad-snouted Caiman" },
  { id: "21", name: "African Slender-snouted Crocodile" },
  { id: "22", name: "Broad-snouted Caiman" },
  { id: "23", name: "Philippine Crocodile" },
  { id: "24", name: "Madagascar Crocodile" },
  { id: "25", name: "Central African Slender-snouted Crocodile" },
];
